# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0006_polloption_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='response',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_by',
        ),
        migrations.AddField(
            model_name='polloption',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
