
# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '11cd9a15c4339d'
# EMAIL_HOST_PASSWORD = '5d53d2f374fc84'
# EMAIL_PORT = 2525
# EMAIL_USE_TLS = False


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

