# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_mgr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref1', models.CharField(max_length=40)),
                ('pref2', models.CharField(max_length=40)),
                ('pref3', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserPreference',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=40, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('confirm_key', models.CharField(default=None, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('stack', models.CharField(max_length=50, null=True)),
                ('git_url', models.URLField(blank=True, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('displayStatus', models.TextField(max_length=1000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=user_mgr.models.get_upload_file_name)),
                ('address', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfile',
            },
        ),
    ]
