# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0003_auto_20170628_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
